-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 16:00:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema P5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema P5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P5` DEFAULT CHARACTER SET utf8 ;
USE `P5` ;

-- -----------------------------------------------------
-- Table `P5`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P5`.`Category` ;

CREATE TABLE IF NOT EXISTS `P5`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `P5`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P5`.`Product` ;

CREATE TABLE IF NOT EXISTS `P5`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `store` VARCHAR(200) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `nutriscore_grade` CHAR(1) NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Category_id`),
  INDEX `fk_Product_Category1_idx` (`Category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `P5`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5`.`Substitution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P5`.`Substitution` ;

CREATE TABLE IF NOT EXISTS `P5`.`Substitution` (
  `Product_id` INT NOT NULL,
  `Product_sub` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Product_sub`),
  INDEX `fk_Product_has_Product_Product1_idx` (`Product_sub` ASC) VISIBLE,
  INDEX `fk_Product_has_Product_Product_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Product_Product`
    FOREIGN KEY (`Product_id`)
    REFERENCES `P5`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Product_Product1`
    FOREIGN KEY (`Product_sub`)
    REFERENCES `P5`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
